# Generated by Django 3.1.5 on 2021-02-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('C', models.IntegerField(default=0)),
                ('D', models.IntegerField(default=0)),
                ('E', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('A', models.IntegerField(default=0)),
                ('B', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LifeInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('A', models.IntegerField(default=0)),
                ('B', models.IntegerField(default=0)),
                ('C', models.IntegerField(default=0)),
                ('F', models.IntegerField(default=0)),
                ('H', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Retirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('J', models.IntegerField(default=0)),
                ('K', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('M', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('Q', models.IntegerField(default=0)),
                ('R', models.IntegerField(default=0)),
                ('S', models.IntegerField(default=0)),
                ('T', models.IntegerField(default=0)),
                ('U', models.IntegerField(default=0)),
            ],
        ),
    ]
