# Generated by Django 3.1.6 on 2021-03-03 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tools', '0002_auto_20210226_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetirementResults',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('J', models.IntegerField(default=0)),
                ('K', models.IntegerField(default=0)),
                ('L', models.IntegerField(default=0)),
                ('M', models.IntegerField(default=0)),
                ('P', models.IntegerField(default=0)),
                ('Q', models.IntegerField(default=0)),
                ('estimatedSavingsNeeded', models.IntegerField(default=0)),
                ('S', models.IntegerField(default=0)),
                ('T', models.IntegerField(default=0)),
                ('estimatedSavingsNeeded65', models.IntegerField(default=0)),
            ],
        ),
        migrations.RenameModel(
            old_name='Budget',
            new_name='BudgetResults',
        ),
        migrations.RenameModel(
            old_name='EmergencyFund',
            new_name='EmergencyFundResults',
        ),
        migrations.RenameModel(
            old_name='LifeInsurance',
            new_name='LifeInsuranceResults',
        ),
        migrations.DeleteModel(
            name='Retirement',
        ),
    ]
