# Generated by Django 3.1.7 on 2021-04-06 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_auto_20210303_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeinsuranceresults',
            name='Result',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='A',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='B',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='C',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='F',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='H',
            field=models.FloatField(default=0.0),
        ),
    ]
