# Generated by Django 3.1.7 on 2021-04-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_auto_20210405_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifeinsuranceresults',
            name='D',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lifeinsuranceresults',
            name='Debt',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lifeinsuranceresults',
            name='E',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lifeinsuranceresults',
            name='Emerg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lifeinsuranceresults',
            name='Finalexp',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='lifeinsuranceresults',
            name='Mortgage',
            field=models.FloatField(default=0.0),
        ),
    ]
