# Generated by Django 3.1.7 on 2021-04-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_auto_20210406_0003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='retirementresults',
            old_name='J',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='K',
            new_name='CurrentIncome',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='L',
            new_name='NRSIContributions',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='M',
            new_name='NRSISavings',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='P',
            new_name='RRSPContributions',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='Q',
            new_name='RRSPSavings',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='S',
            new_name='Result',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='T',
            new_name='RetirementAge',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='estimatedSavingsNeeded',
            new_name='RetirementIncome',
        ),
        migrations.RenameField(
            model_name='retirementresults',
            old_name='estimatedSavingsNeeded65',
            new_name='TFSAContributions',
        ),
        migrations.AddField(
            model_name='retirementresults',
            name='TFSASavings',
            field=models.IntegerField(default=0),
        ),
    ]
