# Generated by Django 3.1.7 on 2021-04-06 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_auto_20210406_0038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyfundresults',
            old_name='A',
            new_name='Current',
        ),
        migrations.RenameField(
            model_name='emergencyfundresults',
            old_name='B',
            new_name='Debt',
        ),
        migrations.AddField(
            model_name='emergencyfundresults',
            name='Insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyfundresults',
            name='Other',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyfundresults',
            name='Recommended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyfundresults',
            name='Remaining',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyfundresults',
            name='Rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyfundresults',
            name='Telecom',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyfundresults',
            name='Transportation',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emergencyfundresults',
            name='Utilities',
            field=models.IntegerField(default=0),
        ),
    ]
