# Generated by Django 3.1.7 on 2021-04-07 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20210406_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetresults',
            name='OtherIncome',
            field=models.IntegerField(default=0),
        ),
    ]
