# Generated by Django 3.1.6 on 2021-04-07 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0008_auto_20210407_0121'),
        ('tools', '0009_budgetresults_otherincome'),
    ]

    operations = [
    ]
