# Generated by Django 3.1.7 on 2021-04-09 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_merge_20210407_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lifeinsuranceresults',
            old_name='A',
            new_name='Education',
        ),
        migrations.RenameField(
            model_name='lifeinsuranceresults',
            old_name='B',
            new_name='Hier',
        ),
        migrations.RenameField(
            model_name='lifeinsuranceresults',
            old_name='C',
            new_name='Insurance',
        ),
        migrations.RenameField(
            model_name='lifeinsuranceresults',
            old_name='D',
            new_name='Kids',
        ),
        migrations.RenameField(
            model_name='lifeinsuranceresults',
            old_name='E',
            new_name='Years',
        ),
        migrations.RemoveField(
            model_name='lifeinsuranceresults',
            name='F',
        ),
    ]
