# Generated by Django 3.1.7 on 2021-04-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0011_auto_20210408_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Debt',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Education',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Emerg',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Finalexp',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='H',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Hier',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Insurance',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Kids',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Mortgage',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='lifeinsuranceresults',
            name='Years',
            field=models.IntegerField(default=0.0),
        ),
    ]
