# Generated by Django 3.1.6 on 2021-04-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_auto_20210409_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lifeinsuranceresults',
            name='H',
        ),
    ]
