# Generated by Django 3.1.6 on 2021-04-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0013_remove_lifeinsuranceresults_h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetresults',
            name='Result1',
        ),
        migrations.RemoveField(
            model_name='budgetresults',
            name='Result2',
        ),
        migrations.RemoveField(
            model_name='budgetresults',
            name='Result3',
        ),
        migrations.RemoveField(
            model_name='budgetresults',
            name='Result4',
        ),
        migrations.RemoveField(
            model_name='budgetresults',
            name='Result5',
        ),
        migrations.RemoveField(
            model_name='budgetresults',
            name='Result6',
        ),
    ]
