# Generated by Django 3.1.6 on 2021-03-23 21:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='group',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='isCompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='related_section',
            field=models.TextField(choices=[('ZERO', 'Unassigned'), ('ONE', 'Personal Section'), ('TWO', 'Mindset Section'), ('THREE', 'Accounts Section'), ('FOUR', 'Assets Section'), ('FIVE', 'Debt Section'), ('SIX', 'Income Section'), ('SEVEN', 'Insurance Section'), ('EIGHT', 'Misc Section')], default=('ZERO', 'Unassigned')),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='resources',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='weight_value',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
