# Generated by Django 3.1.6 on 2021-03-30 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_auto_20210323_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='related_section',
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='weight_value',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='flag',
            field=models.TextField(default='testFlag', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='resources',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
