# Generated by Django 3.1.6 on 2021-03-30 17:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0004_auto_20210330_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='users',
            field=models.ManyToManyField(blank=True, default=None, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
