# Generated by Django 3.1.5 on 2021-03-31 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_auto_20210330_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrecommendation',
            name='recommendation',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='recommendations.recommendation'),
        ),
    ]
