# Generated by Django 3.1.5 on 2021-03-31 22:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0009_auto_20210330_1952'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userrecommendation',
            unique_together={('user', 'recommendation')},
        ),
    ]
