# Generated by Django 3.1.6 on 2021-03-16 01:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('province', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('fin_goal', models.TextField(blank=True, choices=[('EF', 'Build an Emergency Fund'), ('IN', 'Start Investing'), ('RE', 'Save for Retirement'), ('HM', 'Buy a House'), ('DF', 'Pay off Debt'), ('FO', 'Become Financially Organized')], null=True)),
                ('marital_status', models.TextField(blank=True, choices=[('SI', 'Single'), ('MA', 'Married'), ('DV', 'Divorced'), ('WI', 'Widowed'), ('DP', 'Domestic Partner')], null=True)),
                ('number_of_children', models.IntegerField(default=None, null=True)),
                ('budget', models.BooleanField(default=False)),
                ('weekly_finance_check', models.BooleanField(default=False)),
                ('monthly_finance_check', models.BooleanField(default=False)),
                ('updated_will', models.BooleanField(default=False)),
                ('credit_score', models.BooleanField(default=False)),
                ('automated_savings', models.BooleanField(default=False)),
                ('automated_bills', models.BooleanField(default=False)),
                ('household_inventory', models.BooleanField(default=False)),
                ('financial_holdings_inventory', models.BooleanField(default=False)),
                ('review_beneficiaries', models.BooleanField(default=False)),
                ('old_paperwork', models.BooleanField(default=False)),
                ('organized_documents', models.BooleanField(default=False)),
                ('personal_directive', models.BooleanField(default=False)),
                ('power_attorney', models.BooleanField(default=False)),
                ('credit_report', models.BooleanField(default=False)),
                ('overwhelmed', models.BooleanField(default=False)),
                ('pass_manager', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMindset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stress', models.TextField(blank=True, choices=[('NE', 'Never'), ('RA', 'Rarely'), ('OM', 'Once a Month'), ('CM', 'A couple times a Month'), ('OW', 'Once a Week'), ('CW', 'A couple times a Week'), ('DA', 'Daily'), ('CO', 'Constantly'), ('NS', 'Not sure')], null=True)),
                ('feeling', models.TextField(blank=True, choices=[('SR', 'Stressed'), ('CO', 'Concerned'), ('OK', 'Okay'), ('GR', 'Great'), ('NS', 'Not sure')], null=True)),
                ('risk_tol', models.TextField(blank=True, choices=[('CO', 'Conservative'), ('BA', 'Balanced'), ('AG', 'Aggressive'), ('NS', 'Not sure')], null=True)),
                ('willingness', models.TextField(blank=True, choices=[('NA', 'Not at all'), ('SW', 'Somewhat Willing'), ('AW', 'Actively Willing'), ('EW', 'Extremely Willing'), ('NS', 'Not sure')], null=True)),
                ('date_created', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mindset', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInsurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('LI', 'Life Insurance'), ('DI', 'Disability Insurance'), ('CI', 'Critical Illness Insurance')])),
                ('policy_type', models.TextField(choices=[('WL', 'Whole Life'), ('UL', 'Universal Life'), ('TL', 'Term Life')], null=True)),
                ('benefit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserIncome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDebt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('PE', 'Personal Loan'), ('CR', 'Credit Card'), ('SL', 'Student Loan'), ('LC', 'Line of Credit'), ('HE', 'Home Equity Line of Credit'), ('VL', 'Vehicle Loan')])),
                ('amount', models.IntegerField(default=0)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monthly_payment', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('H', 'HOUSE'), ('C', 'CAR'), ('O', 'OTHER')])),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('CQ', 'Chequing'), ('SA', 'Savings'), ('EF', 'Emergency Fund'), ('RR', 'Registered Retirement Savings Plan'), ('LI', 'Locked-In Retirement Account'), ('GR', 'Group Registered Retirement Savings Plan'), ('DC', 'Defined Contribution Pension Plan'), ('DB', 'Defined Benefit Pension Plan'), ('TF', 'Tax Free Savings Account'), ('OT', 'Non-Registered Account')])),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('desc', models.TextField(blank=True, max_length=400, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClientEmployeeInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200, unique=True)),
                ('company', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('account_type', models.TextField(choices=[('ONE', 'Level 1'), ('TWO', 'Level 2'), ('THREE', 'Level 3'), ('FOUR', 'Level 4'), ('FIVE', 'Level 5')], default=('ONE', 'Level 1'))),
                ('preferred_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
