# Generated by Django 3.1.6 on 2021-03-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemployeeinfo',
            name='account_type',
            field=models.TextField(choices=[('ONE', 'Level 1'), ('TWO', 'Level 2'), ('THREE', 'Level 3'), ('FOUR', 'Level 4'), ('FIVE', 'Level 5')], default=('ONE', 'Level 1'), null=True),
        ),
    ]
