# Generated by Django 3.1.5 on 2021-03-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210316_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userassets',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userdebt',
            name='interest',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userincome',
            name='value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='benefit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinsurance',
            name='premium',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='number_of_children',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
