# Generated by Django 3.1.5 on 2021-03-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210318_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdebt',
            name='interest',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
