# Generated by Django 3.1.6 on 2021-03-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210318_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientemployeeinfo',
            name='account_type',
            field=models.TextField(choices=[('ONE', 'Level 1'), ('TWO', 'Level 2'), ('THREE', 'Level 3'), ('FOUR', 'Level 4'), ('FIVE', 'Level 5')], default=('ONE', 'Level 1')),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='automated_bills',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='automated_savings',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='budget',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='credit_report',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='credit_score',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='financial_holdings_inventory',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='household_inventory',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='monthly_finance_check',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='old_paperwork',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='organized_documents',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='overwhelmed',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='pass_manager',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='personal_directive',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='power_attorney',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='review_beneficiaries',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='updated_will',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userpersonal',
            name='weekly_finance_check',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
