# Generated by Django 3.1.6 on 2021-03-30 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210323_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientemployeeinfo',
            name='login_count',
            field=models.IntegerField(default=0),
        ),
    ]
