# Generated by Django 3.1.5 on 2021-03-31 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clientemployeeinfo_login_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpersonal',
            old_name='monthly_finance_check',
            new_name='finance_check',
        ),
        migrations.RemoveField(
            model_name='userpersonal',
            name='weekly_finance_check',
        ),
    ]
