# Generated by Django 3.1.6 on 2021-04-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210331_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermindset',
            name='feeling',
            field=models.TextField(blank=True, choices=[('SR', 'Stressed'), ('CO', 'Concerned'), ('OK', 'Okay'), ('GR', 'Great')], null=True),
        ),
        migrations.AlterField(
            model_name='usermindset',
            name='stress',
            field=models.TextField(blank=True, choices=[('NE', 'Never'), ('RA', 'Rarely'), ('OM', 'Once a Month'), ('CM', 'A couple times a Month'), ('OW', 'Once a Week'), ('CW', 'A couple times a Week'), ('DA', 'Daily'), ('CO', 'Constantly')], null=True),
        ),
    ]
